name = "text-to-coda"
main = "src/index.js"
compatibility_date = "2022-06-22"
node_compat = true

[vars]
DOC_ID = "fuE0EJRftY"
TASK_TABLE_ID = "grid-3l8w7D_AVl"
TYPES_TABLE_ID = "grid-57eD53TLPI"

# The necessary secrets are:
# - CODA_API_KEY
# - OUTBOUND_PHONE
# - TWILIO_AUTH_TOKEN
# Run `wrangler secret put <NAME>` for each of these