name = "text-to-coda"
main = "src/index.js"
compatibility_date = "2022-06-22"
node_compat = true

[vars]
DOC_ID = "8BR8m3RdC_"
TASK_TABLE_ID = "grid-Te4_AGhpYu"
TYPES_TABLE_ID = "grid-VtK-u41v14"

# The necessary secrets are:
# - CODA_API_KEY
# - OUTBOUND_PHONE
# - TWILIO_AUTH_TOKEN
# Run `wrangler secret put <NAME>` for each of these